ci: do ci and build at the same time

diff --git a/.github/workflows/ci-server.yml b/.github/workflows/ci-server.yml
--- a/.github/workflows/ci-server.yml
+++ b/.github/workflows/ci-server.yml
@@ -28,3 +28,14 @@ jobs:
       - name: test
         working-directory: server
         run: go test ./... -v -race
+  ci-server-check:
+    runs-on: ubuntu-latest
+    needs: [ci-server-lint, ci-server-test]
+    if: always()
+    steps:
+      - name: Check if all jobs succeeded
+        run: |
+          if [[ "${{ needs.ci-server-lint.result }}" != "success" ]] || [[ "${{ needs.ci-server-test.result }}" != "success" ]]; then
+            echo "Lint or test failed"
+            exit 1
+          fi
